import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '../../../lib/supabase/server';

type Employee = { id:string; cleaner_id:string; is_active:boolean; created_at:string; profiles:{full_name?:string;phone?:string;email?:string}|null };

export default async function CompanyEmployeesPage() {
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login');
  const {data:company}=await supabase.from('company_profiles').select('id,name,company_code').eq('owner_id',user.id).maybeSingle(); if(!company) redirect('/');
  const {data}=await supabase.from('company_cleaners').select('id,cleaner_id,is_active,created_at,profiles!cleaner_id(full_name,phone,email)').eq('company_id',company.id).order('created_at',{ascending:false});
  const employees=(data??[]) as unknown as Employee[];
  async function toggleEmployee(formData:FormData) { 'use server'; const server=await createClient(); const {data:{user:current}}=await server.auth.getUser(); if(!current) redirect('/login'); const id=String(formData.get('employee_id')); const active=formData.get('active')==='true'; const {data:owned}=await server.from('company_profiles').select('id').eq('owner_id',current.id).maybeSingle(); if(!owned) redirect('/'); const {error}=await server.from('company_cleaners').update({is_active:active}).eq('id',id).eq('company_id',owned.id); if(error) throw new Error(error.message); revalidatePath('/company/employees'); }
  return <div className="mx-auto max-w-3xl px-4 py-10"><Link className="text-sm font-bold text-emerald-700" href="/company">← Кабинет компании</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Сотрудники</h1><p className="mt-2 text-sm text-slate-500">Передайте клинеру код компании: <b>{company.company_code}</b></p></div><div className="rounded-2xl bg-emerald-50 px-5 py-3 text-center"><b className="text-2xl text-emerald-800">{employees.filter(x=>x.is_active).length}</b><p className="text-xs text-emerald-700">активных</p></div></div><div className="mt-6 space-y-3">{employees.length?employees.map(employee=><article className="card flex flex-wrap items-center gap-4" key={employee.id}><div className="grid h-12 w-12 place-items-center rounded-full bg-emerald-100 font-black text-emerald-800">{(employee.profiles?.full_name??'С').slice(0,1)}</div><div className="min-w-0 flex-1"><h2 className="font-black">{employee.profiles?.full_name??'Сотрудник'}</h2><p className="truncate text-sm text-slate-500">{employee.profiles?.phone??employee.profiles?.email??'Контакт не указан'}</p></div><form action={toggleEmployee}><input type="hidden" name="employee_id" value={employee.id}/><input type="hidden" name="active" value={employee.is_active?'false':'true'}/><button className={employee.is_active?'rounded-xl border border-red-200 px-4 py-2 font-semibold text-red-600':'button'}>{employee.is_active?'Отключить':'Включить'}</button></form></article>):<div className="card text-center"><b>Сотрудников пока нет</b><p className="mt-2 text-sm text-slate-500">Клинер должен зарегистрироваться с кодом {company.company_code}.</p></div>}</div></div>;
}
