import { colors, radii, spacing } from '@cleaning-go/ui';
import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions, type TextInputProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export function Screen({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) { const {width}=useWindowDimensions();const compact=width<390;const contentStyle=[s.content,compact&&s.contentCompact,width>760&&s.contentWide];const body = scroll ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={contentStyle}>{children}</ScrollView> : <View style={contentStyle}>{children}</View>; return <SafeAreaView style={s.screen}>{body}</SafeAreaView>; }
export function Title({ children, subtitle }: PropsWithChildren<{ subtitle?: string }>) { const {width}=useWindowDimensions();return <View style={s.titleBlock}><Text style={[s.title,width<390&&s.titleCompact]}>{children}</Text>{subtitle ? <Text style={[s.muted,width<390&&s.mutedCompact]}>{subtitle}</Text> : null}</View>; }
export function Card({ children }: PropsWithChildren) { return <View style={s.card}>{children}</View>; }
export function Field({ label, error, ...props }: TextInputProps & { label: string; error?: string }) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={[s.input, error && s.inputError]} {...props}/>{error ? <Text style={s.error}>{error}</Text> : null}</View>; }
export function Button({ title, onPress, busy, variant='primary', disabled }: { title:string; onPress:()=>void; busy?:boolean; variant?:'primary'|'secondary'|'danger'; disabled?:boolean }) { return <Pressable disabled={disabled||busy} onPress={onPress} style={({pressed})=>[s.button,s[variant],pressed&&s.pressed,disabled&&s.dim]}>{busy?<ActivityIndicator color={variant==='primary'?'white':colors.primary}/>:<Text numberOfLines={2} style={[s.buttonText,variant!=='primary'&&s.secondaryText]}>{title}</Text>}</Pressable>; }
export function EmptyState({ title, body, action }: {title:string;body:string;action?:ReactNode}) { return <Card><Text style={s.cardTitle}>{title}</Text><Text style={s.muted}>{body}</Text>{action}</Card>; }
export function formatMoney(minor:number){return new Intl.NumberFormat('ru-KZ',{style:'currency',currency:'KZT',maximumFractionDigits:0}).format(minor/100);}
export const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F4FAF8'},content:{width:'100%',padding:spacing.lg,gap:spacing.md},contentCompact:{paddingHorizontal:14,paddingVertical:16,gap:12},contentWide:{maxWidth:1120,alignSelf:'center',paddingVertical:40},titleBlock:{gap:5,marginBottom:8},title:{fontSize:30,lineHeight:37,fontWeight:'900',letterSpacing:-.7,color:'#123D35'},titleCompact:{fontSize:25,lineHeight:31,letterSpacing:-.4},muted:{color:'#69817B',lineHeight:21},mutedCompact:{fontSize:13,lineHeight:19},card:{backgroundColor:'rgba(255,255,255,.96)',borderRadius:20,padding:spacing.lg,gap:spacing.sm,borderWidth:1,borderColor:'#E0EEE9',shadowColor:'#143F36',shadowOpacity:.07,shadowRadius:18,shadowOffset:{width:0,height:7},elevation:3},cardTitle:{fontSize:18,fontWeight:'800',color:'#183D35',flexShrink:1},field:{gap:7,minWidth:0},label:{fontWeight:'700',color:'#244A42'},input:{width:'100%',minHeight:50,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#D8E8E3',borderRadius:14,paddingHorizontal:16,paddingVertical:13,color:colors.text,fontSize:16},inputError:{borderColor:colors.danger},error:{color:colors.danger,fontSize:12},button:{minHeight:54,minWidth:0,borderRadius:15,alignItems:'center',justifyContent:'center',paddingHorizontal:16,shadowColor:'#087562',shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:4}},primary:{backgroundColor:'#0B967C'},secondary:{backgroundColor:'#FFFFFF',borderWidth:1.5,borderColor:'#A8D8CC'},danger:{backgroundColor:'#FDEEEE'},buttonText:{color:'white',fontWeight:'800',fontSize:16,lineHeight:20,letterSpacing:.1,textAlign:'center',flexShrink:1},secondaryText:{color:colors.primaryDark},pressed:{transform:[{scale:.985}],opacity:.88},dim:{opacity:.55},row:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center'},badge:{alignSelf:'flex-start',maxWidth:'100%',backgroundColor:colors.primarySoft,color:colors.primaryDark,paddingHorizontal:10,paddingVertical:5,borderRadius:radii.pill,overflow:'hidden'}});
